#!/bin/bash


curl --location --request PATCH 'https://mijn.host/api/v2/domains/bergman.sh/dns' \
--header 'Accept;' \
--header 'User-Agent: my-application/1.0.0' \
--header 'API-Key: YOUR_API_KEY_HERE' \
--header 'Content-Type: application/json' \
--data-raw '{
    "record": {
        "type": "A",
        "name": "foo",
        "value": "127.0.0.1",
        "ttl": 900
    }
}'
